database:
  conn_string: "postgresql://postgres:qwerty@localhost:65432/test_bankapp?sslmode=disable" # Connect to test database from host
  # conn_string: "postgresql://postgres:qwerty@db:65432/test_bankapp?sslmode=disable" # Connect to test database from docker
web_api:
  internal:
    addr: :58001
    cors:
      allowed_origins:
        - "http://localhost:*"
        - "https://localhost:*"
      allowed_methods:
        - "POST"
        - "GET"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed_headers:
        - "*"
      debug: true
      allow_creds: true