database:
#  conn_string: "postgresql://user:password@localhost:15432/db_name?sslmode=disable"
  conn_string: "postgresql://postgres:qwerty@localhost:65432/test_bankapp?sslmode=disable" # Test database
web_api:
  internal:
    addr: :58001
    cors:
      allowed_origins:
        - "http://localhost:*"
        - "https://localhost:*"
      allowed_methods:
        - "POST"
        - "GET"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed_headers:
        - "*"
      debug: true
      allow_creds: true